[package]
name = "redis-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = { version = "0.31.0", features = ["tokio-comp"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
types = { version = "0.1.0", path = "../types" }
